/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuzh_androidtest_jni_Foo */

#ifndef _Included_com_xuzh_androidtest_jni_Foo
#define _Included_com_xuzh_androidtest_jni_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuzh_androidtest_jni_Foo
 * Method:    method1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xuzh_androidtest_jni_Foo_method1
  (JNIEnv *, jobject);

/*
 * Class:     com_xuzh_androidtest_jni_Foo
 * Method:    method2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xuzh_androidtest_jni_Foo_method2
  (JNIEnv *, jobject);

/*
 * Class:     com_xuzh_androidtest_jni_Foo
 * Method:    method3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xuzh_androidtest_jni_Foo_method3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
